project = Project.find(1)
puts "Project: #{project.name}"
puts "Project path: #{project.path}"
puts "Deletion scheduled: #{project.pending_delete?}"
puts "CI/CD enabled: #{project.builds_enabled?}"
puts "Shared runners: #{project.shared_runners_enabled?}"
puts "Pipelines count: #{project.ci_pipelines.count}"
puts "Default branch: #{project.default_branch}"
puts "Repository empty: #{project.repository.empty?}"
puts "Repository exists: #{project.repository.exists?}"
puts "Archived: #{project.archived?}"
